### database
services:
  mysql:
    image: "mysql:8.1"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_USER: speed
#      MYSQL_PASSWORD: test
#      MYSQL_DATABASE: speedtest
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - /mnt/mysql:/var/lib/mysql
      - ./speedtest/results/telemetry_mysql.sql:/root/telemetry_mysql.sql
#    deploy:
#      placement:
#        constraints:
#          - node.role == manager
 #   networks:
 #     - net_db_vot
    networks:
      net: {}

### app
  app:
    build: ./speedtest
#    image: app:latest
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./speedtest/docker/servers.json:/var/www/html/servers.json
    environment:
      db_type: ${db_type}
      MODE: ${MODE}
      TELEMETRY: ${TLM}
      ENABLE_ID_OBFUSCATION: ${EIO}
      REDACT_IP_ADDRESSES: ${RIA}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PASSWORD: ${stats_password}
#      MODE: frontend
#      TELEMETRY: true
#      ENABLE_ID_OBFUSCATION: true
#      REDACT_IP_ADDRESSES: false
    depends_on:
      - mysql
    ports:
      - "80:80"
#    deploy:
#      placement:
#        constraints:
#          - node.role == manager
#    networks:
#      - net_vot_nginx
#      - net_db_vot
    networks:
      net: {}

networks:
  net:
    external:
      name: traefik-public
#  net_vot_nginx:
#  net_db_vot:
