services:
  fluentd:
    build: ./fluentd
    links:
      - "elasticsearch"
#    environment:
#      - LOG_TYPE: elasticsearch
#      - LOG_HOST: elasticsearch
#      - LOG_PORT: 9200
    volumes:
      - ./fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
    networks:
      - traefik-public

  elasticsearch:
    image: elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
      - node.name=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=DockerRocks!
    ports:
      - "9200:9200"
    networks:
      - traefik-public

  kibana:
    image: kibana:7.6.2
#    mem_limit: "4294967296"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - ELASTICSEARCH_USERNAME=rebrainme
      - ELASTICSEARCH_PASSWORD=DockerRocks!
    links:
      - "elasticsearch"
#    ports:
#      - "5601:5601"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: kibana.access
#    deploy:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.kibana.entrypoints=http"
      - "traefik.http.routers.kibana.rule=HostRegexp(`kibana.{host:.+}.nip.io`)"
      - "traefik.http.services.kibana-service.loadbalancer.server.port=5601"
#      - "traefik.http.middlewares.kibana-auth.basicauth.users=rebrainme:$$apr1$$M2y3w41L$$XejqYC2itrGuUIXwDCInf."
#      - "traefik.http.routers.kibana.middlewares=kibana-auth"
    depends_on:
      - elasticsearch
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
#networks:
#  net:
#    external:
#      name: traefik-public
