services:
  traefik:
    image: "traefik:v2.11"
#    command: --api.insecure=true --api.dashboard --entrypoints.web.address=:5601 --entrypoints.http.address=:80 --providers.docker --providers.docker.swarmMode
    command: --api.insecure=true --api.dashboard -entrypoints.http.address=:80 --providers.docker --providers.docker.swarmMode
    container_name: traefik
    ports:
#      - "5601:5601"
      - "80:80"
      - "8080:8080"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: traefik.access
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.traefik.rule=Host(`traefik.nip.io`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.traefik-service.loadbalancer.server.port=888"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      net: {}

networks:
  net:
    external:
      name: traefik-public
