providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik-public"

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: :80
